version = 0.1
[default.deploy.parameters]
stack_name = "pipeline-test-harness"
resolve_s3 = true
s3_prefix = "pipeline-test-harness"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
