name: Cleanup Sandbox

on:
  workflow_run:
    workflows: ["Dependabot Merge"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup-sandbox:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World"