name: Deploy Sandbox
run-name: Deploy ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }} to Sandbox

on:
  push:
  pull_request:
    branches:
      - main
  delete:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}

env:
  MY_TEST_VAR: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}
  APP_NAME: test-api

permissions:
  contents: write
  pull-requests: write

jobs:
  get-branch-name:
    name: Get branch name
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.branch-name.outputs.BRANCH_NAME }}
    steps:
      - id: branch-name
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "var 0 $MY_TEST_VAR"
          echo "var 1 --- ${{ github.event.pull_request.head.ref }}"
          echo "var 2 --- ${{ github.ref_name }}"
          echo "var 3 ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}"
          echo "var 4 ${{github.event.number}}"
          REF_VALUE=$(echo "${{ github.event.ref || github.ref }}")
          REPLACE_STRING="refs/heads/"
          EMPTY_STRING=""
          BRANCH_NAME=$(echo "PR-${{github.event.number}}")
          if [[ $BRANCH_NAME =~ ^dependabot\/.* ]]; then
            stackName="$APP_NAME-PR${{github.event.number}}"
            echo "STACK_NAME=$stackName" >> $GITHUB_OUTPUT
            echo "### Stack Name: $stackName" >> $GITHUB_STEP_SUMMARY
          else
            branchName=$(echo "$BRANCH_NAME" | tr '.' '_' | tr '/' '_' | tr '[:upper:]' '[:lower:]')
            branchName="${branchName:0:9}"
            stackName="$APP_NAME-$branchName"
            echo "STACK_NAME=$stackName" >> $GITHUB_OUTPUT
            echo "### Stack Name: $stackName" >> $GITHUB_STEP_SUMMARY
          fi

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "### Branch Name $BRANCH_NAME" >> $GITHUB_STEP_SUMMARY

  review-and-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: ./.github/workflows/dependabot-merge.yaml
    secrets: inherit

  dependabot-cleanup:
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: [review-and-merge]
    uses: ./.github/workflows/cleanup-sandbox.yaml
    secrets: inherit