name: Deploy Test
run-name: Deploy ${{ github.ref_name }} to Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/shared-lint.yaml
    secrets: inherit

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/shared-unit-tests.yaml
    secrets: inherit

  deploy-stacks:
    name: Deploy stacks
    needs: [lint, unit-tests]
    uses: ./.github/workflows/shared-sam-build-and-deploy.yaml
    with:
      WORKFLOW_ENV: TEST
      AWS_REGION: us-gov-west-1
      USER_SERVICE_API_URL: https://qa-cloud-services.tylerapp.com/api/user-service
      DATA_BOUNDARY_SERVICE_API_URL: https://qa-cloud-services.tylerapp.com/api/data-boundary-service
    secrets: inherit

  update-policy:
    name: Update Policy
    needs: [deploy-stacks]
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-gov-west-1
          role-to-assume: ${{ vars.PIPELINE_EXECUTION_ROLE }}
          role-session-name: discovery-update-policy
          role-duration-seconds: 3600
          role-skip-session-tagging: true
      - name: Update Policy
        uses: tyler-technologies/cj-jpp-build-authorizer-policy-action@master
        with:
          oasFileName: ./schemas/openapi.yaml
          tableName: electronic-discovery

  test-api:
    name: Test API
    needs: [update-policy]
    uses: ./.github/workflows/shared-test-api.yaml
    with:
      WORKFLOW_ENV: TEST
      BASE_URL: https://qa-discovery.tylerapp.com/api
    secrets: inherit

  run-security-tests:
    name: Run Security Tests
    needs: [update-policy]
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Security Tests
        env:
          ENV: TEST
          NPM_ARTIFACTORY_AUTH: ${{ secrets.SCRATCH_ARTIFACTORY_TOKEN }}
          OKTA_AUTH_SERVER_URL: ${{ vars.TEST_OKTA_AUTH_SERVER_URL }}
          OKTA_AUTH_CLIENT_ID: ${{ vars.TEST_OKTA_AUTH_CLIENT_ID }}
          OKTA_AUTH_CLIENT_SECRET: ${{ secrets.TEST_OKTA_AUTH_CLIENT_SECRET }}
          BASE_URL: https://qa-discovery.tylerapp.com/api
        run: |
          npm config set registry https://tylertech.jfrog.io/tylertech/api/npm/npm
          npm config set //tylertech.jfrog.io/tylertech/api/npm/:_auth "$NPM_ARTIFACTORY_AUTH"
          npm ci
          node tools/security-tests/index.js

  update-data-models:
    name: Update Data Models
    needs: [deploy-stacks]
    permissions:
      contents: write
    uses: ./.github/workflows/shared-update-data-models.yaml
    secrets: inherit

  update-openapi-docs:
    name: Update OpenAPI docs
    needs: [deploy-stacks]
    permissions:
      contents: write
    uses: ./.github/workflows/shared-update-openapi-documentations.yaml
    secrets: inherit

