name: Deploy Sandbox
run-name: Deploy ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }} to Sandbox

on:
  pull_request:
    branches:
      - main
  delete:
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}

permissions:
  id-token: write
  contents: read
  
env:
  VAR_1: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}

jobs:
  get-branch-name:
    name: Get branch name
    runs-on: ubuntu-latest
    env:
      VAR_2: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}
    outputs:
      BRANCH_NAME: ${{ steps.branch-name.outputs.BRANCH_NAME }}
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.PIPELINE_EXECUTION_ROLE }}
          role-session-name: get-api-base-url
          role-duration-seconds: 3600
          role-skip-session-tagging: true
      - id: branch-name
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          VAR_3: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}
        run: |
          url=$(aws cloudformation describe-stacks --stack-name electronic-discovery-service-$VAR_1)
          echo "Hello $url"
          echo "var1 -> $VAR_1"
          echo "var2 -> $VAR_2"
          echo "var3 -> $VAR_3"
