name: Deploy Sandbox
run-name: Deploy ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }} to Sandbox

on:
  pull_request:
    branches:
      - main
  delete:
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}

env:
  VAR_1: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}

jobs:
  get-branch-name:
    name: Get branch name
    runs-on: ubuntu-latest
    env:
      VAR_2: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}
    outputs:
      BRANCH_NAME: ${{ steps.branch-name.outputs.BRANCH_NAME }}
    steps:
      - id: branch-name
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          VAR_3: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}
        run: |
          echo "var1 -> $VAR_1"
          echo "var2 -> $VAR_2"
          echo "var3 -> $VAR_3"
