name: Deploy Sandbox
run-name: Deploy ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }} to Sandbox

on:
  pull_request:
    branches:
      - main
  delete:
    branches-ignore:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref_name }}

env:
  MY_TEST_VAR: ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  get-branch-name:
    name: Get branch name
    runs-on: ubuntu-latest
    outputs:
      BRANCH_NAME: ${{ steps.branch-name.outputs.BRANCH_NAME }}
    steps:
      - id: branch-name
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "var 0 $MY_TEST_VAR"
          echo "var 1 --- ${{ github.event.pull_request.head.ref }}"
          echo "var 2 --- ${{ github.ref_name }}"
          echo "var 3 ${{ github.event_name == 'workflow_dispatch' && github.ref_name || github.event_name == 'pull_request' && github.head_ref  || github.event_name == 'delete' && github.event.ref }}"

          REF_VALUE=$(echo "${{ github.event.ref || github.ref }}")
          REPLACE_STRING="refs/heads/"
          EMPTY_STRING=""
          BRANCH_NAME=$(echo "${REF_VALUE/"$REPLACE_STRING"/"$EMPTY_STRING"}")

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "### Branch Name $BRANCH_NAME" >> $GITHUB_STEP_SUMMARY

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve a PR
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}