name: Update OpenAPI Based Documentation

on:
  workflow_call:

jobs:
  generate-openapi-based-docs:
    name: Generate OpenAPI Based Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Configure NPM
        env:
          NPM_ARTIFACTORY_AUTH: ${{ secrets.SCRATCH_ARTIFACTORY_TOKEN }}
        run: |
          npm config set registry https://tylertech.jfrog.io/tylertech/api/npm/npm
          npm config set //tylertech.jfrog.io/tylertech/api/npm/:_auth "$NPM_ARTIFACTORY_AUTH"
      - name: Run Tools
        run: |
          # npm install -g redoc-cli
          npm install

          npm run generate-role-docs
          npm run generate-implemented-endpoint-report
          # redoc-cli build ./schemas/openapi.yaml
          # mv redoc-static.html docs/api.html
          if [ -n "$(git status --porcelain --ignored=matching | grep -E -i 'docs/api-implementation-status.md|docs/api.html|docs/authorization/roles.md')" ]; then
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            # git add "docs/api.html" -f
            git add "docs/api-implementation-status.md" -f
            git add "docs/authorization/roles.md" -f
            git commit -m "[skip ci] Update OpenAPI Based Documentation"
            git push
          else
            echo "no changes";
          fi
