name: Portman Tests

on:
  workflow_call:
    inputs:
      WORKFLOW_ENV:
        description: GitHub workflow environment to be able to access environment level secrets. Expected values - TEST, STAGE, PRODUCTION
        required: true
        type: string
      BASE_URL:
        required: true
        type: string

jobs:
  portman:
    name: Run Portman
    runs-on: ubuntu-latest
    environment: ${{ inputs.WORKFLOW_ENV }}
    steps:
      - uses: actions/checkout@v3
      - name: Test API
        env:
          BASE_URL: ${{ inputs.BASE_URL }}
          TEST_USER_SUB: ${{ vars.TEST_USER_SUB }}
          ENV: ${{ inputs.WORKFLOW_ENV }}
          NPM_ARTIFACTORY_AUTH: ${{ secrets.SCRATCH_ARTIFACTORY_TOKEN }}
          OKTA_AUTH_SERVER_URL: ${{ vars.TEST_OKTA_AUTH_SERVER_URL }}
          OKTA_AUTH_CLIENT_ID: ${{ vars.TEST_OKTA_AUTH_CLIENT_ID }}
          OKTA_AUTH_CLIENT_SECRET: ${{ secrets.TEST_OKTA_AUTH_CLIENT_SECRET }}
        run: |
          npm config set registry https://tylertech.jfrog.io/tylertech/api/npm/npm
          npm config set //tylertech.jfrog.io/tylertech/api/npm/:_auth "$NPM_ARTIFACTORY_AUTH"
          npm i -g replace-in-files-cli
          npm ci
          npm run set-portman-config ./portman/portman-cli.json
          npx @apideck/portman --cliOptionsFile portman/portman-cli.json