name: Workflow

on:
  workflow_dispatch:

jobs:
  pre-deployment-validations:
    uses: ./.github/workflows/visualize-a-workflow-pre.yaml
    secrets: inherit

  deployment:
    needs: [pre-deployment-validations]
    uses: ./.github/workflows/visualize-a-workflow-deploy.yaml
    secrets: inherit

  seed:
    needs: [deployment]
    uses: ./.github/workflows/visualize-a-workflow-seed.yaml
    secrets: inherit

  post-deployment-validations:
    needs: [seed]
    uses: ./.github/workflows/visualize-a-workflow-post.yaml
    secrets: inherit