name: Workflow
run-name: Deploy ${{ github.event.pull_request.head.ref || github.ref_name }} to Sandbox

on:
  workflow_call:

jobs:
  seed:
    name: Seed
    runs-on: ubuntu-latest
    steps:
      - name: Seed
        run: |
          echo "seed"